language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database baobab_test;' -U postgres
  - mkdir tests/uploads_for_test
script:
  - pytest
after_script:
  - rm -rf tests/uploads_for_test
