version: '3.7'

services:
  web:
    build: ./api
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=komlan55
      - POSTGRES_PASSWORD=gourami55
      - POSTGRES_DB=baobab_dev

volumes:
  postgres_data:
