"""empty message

Revision ID: 017fa567da49
Revises: 
Create Date: 2020-04-15 23:15:17.576258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017fa567da49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('role', sa.String(), nullable=False))
    op.drop_constraint('permission_role_id_fkey', 'permission', type_='foreignkey')
    op.create_foreign_key(None, 'permission', 'role', ['role'], ['type'])
    op.drop_column('permission', 'role_id')
    op.drop_constraint('role_type_key', 'role', type_='unique')
    op.drop_column('role', 'id')
    op.add_column('user', sa.Column('role', sa.String(), nullable=True))
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role'], ['type'])
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'role')
    op.add_column('role', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.create_unique_constraint('role_type_key', 'role', ['type'])
    op.add_column('permission', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.create_foreign_key('permission_role_id_fkey', 'permission', 'role', ['role_id'], ['id'])
    op.drop_column('permission', 'role')
    # ### end Alembic commands ###
