"""adapt payment type for many to many relationship

Revision ID: 66a8551bf10d
Revises: cbf1f45f4eee
Create Date: 2020-02-22 16:55:31.717558

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a8551bf10d'
down_revision = 'cbf1f45f4eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('payment_type_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], ),
    sa.PrimaryKeyConstraint('payment_type_id', 'business_id')
    )
    op.drop_constraint('business_payment_type_fkey', 'business', type_='foreignkey')
    op.drop_column('business', 'payment_type')
    op.add_column('payment_type', sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(choices=[("credit", "credit"),
                                                                                        ("debit", "debit"),
                                                                                        ("cash", "cash"),
                                                                                        ("crypto", "crypto"),
                                                                                        ]), default="cash"))
    op.drop_constraint('payment_type_name_key', 'payment_type', type_='unique')
    op.drop_column('payment_type', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_type', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('payment_type_name_key', 'payment_type', ['name'])
    op.drop_column('payment_type', 'type')
    op.add_column('business', sa.Column('payment_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('business_payment_type_fkey', 'business', 'payment_type', ['payment_type'], ['id'])
    op.drop_table('payment_types')
    # ### end Alembic commands ###
