"""remove owner

Revision ID: 67ad42d333f3
Revises: 8683cbeb060f
Create Date: 2020-03-01 18:19:37.154063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ad42d333f3'
down_revision = '8683cbeb060f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('owner')
    op.drop_constraint('business_owner_id_fkey', 'business', type_='foreignkey')
    op.drop_column('business', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('business_owner_id_fkey', 'business', 'owner', ['owner_id'], ['id'])
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='owner_pkey')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_pkey')
    )
    # ### end Alembic commands ###
