"""Update social links

Revision ID: 76cb4f9291c8
Revises: 29ed5a7ccccd
Create Date: 2020-02-11 20:43:42.910283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cb4f9291c8'
down_revision = '29ed5a7ccccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_link', sa.Column('business_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'social_link', 'business', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_link', type_='foreignkey')
    op.drop_column('social_link', 'business_id')
    # ### end Alembic commands ###
