"""remove table payment types

Revision ID: 8683cbeb060f
Revises: ec78421eff83
Create Date: 2020-02-29 17:22:06.631296

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8683cbeb060f'
down_revision = 'ec78421eff83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_types')
    op.drop_table('payment_type')
    op.add_column('business', sa.Column('payment_types', sqlalchemy_utils.types.scalar_list.ScalarListType(),
                                        default=["cash"], nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'payment_types')
    op.create_table('payment_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('payment_type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payment_types',
    sa.Column('payment_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='payment_types_business_id_fkey'),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], name='payment_types_payment_type_id_fkey'),
    sa.PrimaryKeyConstraint('payment_type_id', 'business_id', name='payment_types_pkey')
    )
    # ### end Alembic commands ###
