"""update phone table

Revision ID: b5c6453e4672
Revises: 76cb4f9291c8
Create Date: 2020-02-15 19:37:29.978417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c6453e4672'
down_revision = '76cb4f9291c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phones')
    op.drop_column('business', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('phones',
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='phones_business_id_fkey'),
    sa.PrimaryKeyConstraint('number', name='phones_pkey')
    )
    op.drop_table('phone')
    # ### end Alembic commands ###
