"""rename permission field

Revision ID: cbb3e54190ed
Revises: 69bfec2bd4d1
Create Date: 2020-04-13 20:19:04.077023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb3e54190ed'
down_revision = '69bfec2bd4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('model', sa.String(), nullable=False))
    op.drop_column('permission', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('permission', 'model')
    # ### end Alembic commands ###
