"""Add business status

Revision ID: cbf1f45f4eee
Revises: f19b52fac651
Create Date: 2020-02-19 22:46:05.707135

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cbf1f45f4eee'
down_revision = 'f19b52fac651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business',
                  sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(choices=[("pending", "pending"),
                                                                                        ("accepted", "accepted"),
                                                                                        ("refused", "refused"),
                                                                                        ]), default="pending"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'status')
    # ### end Alembic commands ###
