""" Update accepted column

Revision ID: df77c15e6a79
Revises: b5c6453e4672
Create Date: 2020-02-16 14:53:42.192242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df77c15e6a79'
down_revision = 'b5c6453e4672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.drop_column('business', 'accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('business', 'accepted_at')
    # ### end Alembic commands ###
