"""switch deactivated_at to deleted_at


Revision ID: e5940d9abae9
Revises: 3a4ebab98580
Create Date: 2020-03-31 09:31:20.177473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5940d9abae9'
down_revision = '3a4ebab98580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('business', 'deactivated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('deactivated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('business', 'deleted_at')
    # ### end Alembic commands ###
